name: CommFWD
favicon: null
layout_spectrum: 0.8035313526634127
typography_spectrum: 0.7853232375346124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94a8a9'
    - '#2b152a'
    - '#6c8297'
    - '#e4e4c0'
    - '#554248'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
